import { WebClient } from '@slack/web-api'
import { getConfig } from '../config'
import type { MeetingData } from './markdown'

export async function publishToSlack(data: MeetingData, notionPageId?: string): Promise<void> {
  const config = getConfig()

  if (!config.slack.enabled || !config.slack.token || !config.slack.channel) {
    throw new Error('Slack integration not configured')
  }

  const client = new WebClient(config.slack.token)

  const dateStr = data.startedAt.toISOString().split('T')[0]
  const timeStr = `${data.startedAt.getHours().toString().padStart(2, '0')}:${data.startedAt.getMinutes().toString().padStart(2, '0')}`
  const durationMin = Math.ceil(data.transcript.duration / 60)

  // Extract first 3 lines of summary for preview
  const summaryPreview = data.summary.split('\n').filter(l => l.trim()).slice(0, 5).join('\n')

  const blocks = [
    {
      type: 'header',
      text: {
        type: 'plain_text',
        text: `Meeting Notes — ${dateStr} ${timeStr}`
      }
    },
    {
      type: 'section',
      fields: [
        { type: 'mrkdwn', text: `*Duration:* ${durationMin}min` },
        { type: 'mrkdwn', text: `*Language:* ${data.transcript.language}` }
      ]
    },
    { type: 'divider' },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: summaryPreview
      }
    }
  ]

  // Add Notion link if available
  if (notionPageId) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `<https://notion.so/${notionPageId.replace(/-/g, '')}|View full notes in Notion>`
      }
    } as typeof blocks[number])
  }

  blocks.push({
    type: 'context',
    elements: [{ type: 'mrkdwn', text: '_Generated by meeting-note_' }]
  } as typeof blocks[number])

  await client.chat.postMessage({
    channel: config.slack.channel,
    blocks,
    text: `Meeting Notes — ${dateStr} ${timeStr}` // fallback
  })
}
